ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'Van';
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "odometerKm" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "acquisitionCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "region" TEXT;

ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "licenseCategory" TEXT NOT NULL DEFAULT 'LMV';
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "contactNumber" TEXT NOT NULL DEFAULT '';

ALTER TABLE "MaintenanceLog" ADD COLUMN IF NOT EXISTS "cost" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "plannedDistanceKm" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "finalOdometerKm" DOUBLE PRECISION;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "fuelConsumedLiters" DOUBLE PRECISION;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "revenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
